// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminDashboardStats = `-- name: AdminDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM events) AS total_events,
    (SELECT COUNT(*) FROM events WHERE status = 'published') AS published_events,
    (SELECT COUNT(*) FROM bookings) AS total_bookings,
    (SELECT COUNT(*) FROM bookings WHERE status = 'confirmed') AS confirmed_bookings,
    (SELECT COALESCE(SUM(total_amount), 0)::bigint FROM bookings WHERE status = 'confirmed') AS total_revenue,
    (SELECT COALESCE(SUM(sold_count), 0)::bigint FROM ticket_types) AS tickets_sold
`

type AdminDashboardStatsRow struct {
	TotalEvents       int64       `json:"total_events"`
	PublishedEvents   int64       `json:"published_events"`
	TotalBookings     int64       `json:"total_bookings"`
	ConfirmedBookings int64       `json:"confirmed_bookings"`
	TotalRevenue      int64 `json:"total_revenue"`
	TicketsSold       int64 `json:"tickets_sold"`
}

func (q *Queries) AdminDashboardStats(ctx context.Context) (AdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, adminDashboardStats)
	var i AdminDashboardStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.PublishedEvents,
		&i.TotalBookings,
		&i.ConfirmedBookings,
		&i.TotalRevenue,
		&i.TicketsSold,
	)
	return i, err
}

const adminListBookings = `-- name: AdminListBookings :many
SELECT b.id, b.user_id, b.event_id, b.status, b.hold_expires_at, b.total_amount, b.idempotency_key, b.created_at, b.confirmed_at,
       u.email AS user_email,
       u.full_name AS user_name,
       e.title AS event_title,
       e.slug AS event_slug
FROM bookings b
JOIN users u ON b.user_id = u.id
JOIN events e ON b.event_id = e.id
WHERE ($1::text IS NULL OR $1 = '' OR b.status::text = $1)
  AND ($2::text IS NULL OR $2 = '' OR b.event_id = $2::uuid)
ORDER BY b.created_at DESC
LIMIT $3 OFFSET $4
`

type AdminListBookingsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type AdminListBookingsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EventID        uuid.UUID          `json:"event_id"`
	Status         string             `json:"status"`
	HoldExpiresAt  time.Time          `json:"hold_expires_at"`
	TotalAmount    int64              `json:"total_amount"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	UserEmail      string             `json:"user_email"`
	UserName       string             `json:"user_name"`
	EventTitle     string             `json:"event_title"`
	EventSlug      string             `json:"event_slug"`
}

func (q *Queries) AdminListBookings(ctx context.Context, arg AdminListBookingsParams) ([]AdminListBookingsRow, error) {
	rows, err := q.db.Query(ctx, adminListBookings,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListBookingsRow{}
	for rows.Next() {
		var i AdminListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.HoldExpiresAt,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.UserEmail,
			&i.UserName,
			&i.EventTitle,
			&i.EventSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminBookings = `-- name: CountAdminBookings :one
SELECT COUNT(*) FROM bookings b
WHERE ($1::text IS NULL OR $1 = '' OR b.status::text = $1)
  AND ($2::text IS NULL OR $2 = '' OR b.event_id = $2::uuid)
`

type CountAdminBookingsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAdminBookings(ctx context.Context, arg CountAdminBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminBookings, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllEvents = `-- name: CountAllEvents :one
SELECT COUNT(*) FROM events e
WHERE ($1::text IS NULL OR $1 = '' OR e.status::text = $1)
  AND ($2::text IS NULL OR $2 = '' OR e.title ILIKE '%' || $2 || '%')
`

type CountAllEventsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllEvents(ctx context.Context, arg CountAllEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllEvents, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT e.id, e.slug, e.title, e.description, e.venue_id, e.cover_image_url, e.status, e.starts_at, e.ends_at, e.metadata, e.created_at, e.updated_at, v.name AS venue_name, v.city AS venue_city
FROM events e
LEFT JOIN venues v ON e.venue_id = v.id
WHERE ($1::text IS NULL OR $1 = '' OR e.status::text = $1)
  AND ($2::text IS NULL OR $2 = '' OR e.title ILIKE '%' || $2 || '%')
ORDER BY e.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAllEventsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAllEventsRow struct {
	ID            uuid.UUID   `json:"id"`
	Slug          string      `json:"slug"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	VenueID       pgtype.UUID `json:"venue_id"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	Status        string      `json:"status"`
	StartsAt      time.Time   `json:"starts_at"`
	EndsAt        time.Time   `json:"ends_at"`
	Metadata      []byte      `json:"metadata"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	VenueName     pgtype.Text `json:"venue_name"`
	VenueCity     pgtype.Text `json:"venue_city"`
}

func (q *Queries) ListAllEvents(ctx context.Context, arg ListAllEventsParams) ([]ListAllEventsRow, error) {
	rows, err := q.db.Query(ctx, listAllEvents,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEventsRow{}
	for rows.Next() {
		var i ListAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.VenueID,
			&i.CoverImageUrl,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
