// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveHoldsByUser = `-- name: CountActiveHoldsByUser :one
SELECT COUNT(*) FROM bookings
WHERE user_id = $1 AND status IN ('held', 'pending_payment')
`

func (q *Queries) CountActiveHoldsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHoldsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveHoldsByUserForEvent = `-- name: CountActiveHoldsByUserForEvent :one
SELECT COUNT(*) FROM bookings
WHERE user_id = $1 AND event_id = $2 AND status IN ('held', 'pending_payment')
`

type CountActiveHoldsByUserForEventParams struct {
	UserID  uuid.UUID `json:"user_id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) CountActiveHoldsByUserForEvent(ctx context.Context, arg CountActiveHoldsByUserForEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHoldsByUserForEvent, arg.UserID, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (user_id, event_id, status, hold_expires_at, total_amount, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at
`

type CreateBookingParams struct {
	UserID         uuid.UUID `json:"user_id"`
	EventID        uuid.UUID `json:"event_id"`
	Status         string    `json:"status"`
	HoldExpiresAt  time.Time `json:"hold_expires_at"`
	TotalAmount    int64     `json:"total_amount"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.EventID,
		arg.Status,
		arg.HoldExpiresAt,
		arg.TotalAmount,
		arg.IdempotencyKey,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createBookingItem = `-- name: CreateBookingItem :one
INSERT INTO booking_items (booking_id, ticket_type_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, ticket_type_id, quantity, unit_price
`

type CreateBookingItemParams struct {
	BookingID    uuid.UUID `json:"booking_id"`
	TicketTypeID uuid.UUID `json:"ticket_type_id"`
	Quantity     int32     `json:"quantity"`
	UnitPrice    int64     `json:"unit_price"`
}

func (q *Queries) CreateBookingItem(ctx context.Context, arg CreateBookingItemParams) (BookingItem, error) {
	row := q.db.QueryRow(ctx, createBookingItem,
		arg.BookingID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i BookingItem
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getBookingByIDAdmin = `-- name: GetBookingByIDAdmin :one
SELECT b.id, b.user_id, b.event_id, b.status, b.hold_expires_at, b.total_amount, b.idempotency_key, b.created_at, b.confirmed_at,
       u.email AS user_email,
       u.full_name AS user_name,
       e.title AS event_title,
       e.slug AS event_slug
FROM bookings b
JOIN users u ON b.user_id = u.id
JOIN events e ON b.event_id = e.id
WHERE b.id = $1
`

type GetBookingByIDAdminRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EventID        uuid.UUID          `json:"event_id"`
	Status         string             `json:"status"`
	HoldExpiresAt  time.Time          `json:"hold_expires_at"`
	TotalAmount    int64              `json:"total_amount"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	UserEmail      string             `json:"user_email"`
	UserName       string             `json:"user_name"`
	EventTitle     string             `json:"event_title"`
	EventSlug      string             `json:"event_slug"`
}

func (q *Queries) GetBookingByIDAdmin(ctx context.Context, id uuid.UUID) (GetBookingByIDAdminRow, error) {
	row := q.db.QueryRow(ctx, getBookingByIDAdmin, id)
	var i GetBookingByIDAdminRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UserEmail,
		&i.UserName,
		&i.EventTitle,
		&i.EventSlug,
	)
	return i, err
}

const getBookingByIDForUser = `-- name: GetBookingByIDForUser :one
SELECT id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at FROM bookings WHERE id = $1 AND user_id = $2
`

type GetBookingByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBookingByIDForUser(ctx context.Context, arg GetBookingByIDForUserParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIDForUser, arg.ID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getBookingByIdempotencyKey = `-- name: GetBookingByIdempotencyKey :one
SELECT id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at FROM bookings WHERE idempotency_key = $1
`

func (q *Queries) GetBookingByIdempotencyKey(ctx context.Context, idempotencyKey string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIdempotencyKey, idempotencyKey)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listBookingItems = `-- name: ListBookingItems :many
SELECT bi.id, bi.booking_id, bi.ticket_type_id, bi.quantity, bi.unit_price, tt.name AS ticket_type_name
FROM booking_items bi
JOIN ticket_types tt ON bi.ticket_type_id = tt.id
WHERE bi.booking_id = $1
`

type ListBookingItemsRow struct {
	ID             uuid.UUID `json:"id"`
	BookingID      uuid.UUID `json:"booking_id"`
	TicketTypeID   uuid.UUID `json:"ticket_type_id"`
	Quantity       int32     `json:"quantity"`
	UnitPrice      int64     `json:"unit_price"`
	TicketTypeName string    `json:"ticket_type_name"`
}

func (q *Queries) ListBookingItems(ctx context.Context, bookingID uuid.UUID) ([]ListBookingItemsRow, error) {
	rows, err := q.db.Query(ctx, listBookingItems, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingItemsRow{}
	for rows.Next() {
		var i ListBookingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT b.id, b.user_id, b.event_id, b.status, b.hold_expires_at, b.total_amount, b.idempotency_key, b.created_at, b.confirmed_at, e.title AS event_title, e.slug AS event_slug, e.starts_at AS event_starts_at
FROM bookings b
JOIN events e ON b.event_id = e.id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListBookingsByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	EventID        uuid.UUID          `json:"event_id"`
	Status         string             `json:"status"`
	HoldExpiresAt  time.Time          `json:"hold_expires_at"`
	TotalAmount    int64              `json:"total_amount"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	EventTitle     string             `json:"event_title"`
	EventSlug      string             `json:"event_slug"`
	EventStartsAt  time.Time          `json:"event_starts_at"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserRow{}
	for rows.Next() {
		var i ListBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.HoldExpiresAt,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.EventTitle,
			&i.EventSlug,
			&i.EventStartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredHeldBookings = `-- name: ListExpiredHeldBookings :many
SELECT id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at FROM bookings
WHERE status = 'held' AND hold_expires_at < NOW()
LIMIT $1
`

func (q *Queries) ListExpiredHeldBookings(ctx context.Context, limit int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listExpiredHeldBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.HoldExpiresAt,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingPaymentBookings = `-- name: ListExpiredPendingPaymentBookings :many
SELECT id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at FROM bookings
WHERE status = 'pending_payment' AND hold_expires_at < NOW()
LIMIT $1
`

func (q *Queries) ListExpiredPendingPaymentBookings(ctx context.Context, limit int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingPaymentBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Status,
			&i.HoldExpiresAt,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, confirmed_at = $3
WHERE id = $1
RETURNING id, user_id, event_id, status, hold_expires_at, total_amount, idempotency_key, created_at, confirmed_at
`

type UpdateBookingStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status, arg.ConfirmedAt)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.HoldExpiresAt,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}
