// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedEvents = `-- name: CountPublishedEvents :one
SELECT COUNT(*) FROM events e
LEFT JOIN venues v ON e.venue_id = v.id
WHERE e.status = 'published'
  AND ($1::text IS NULL OR $1 = '' OR e.title ILIKE '%' || $1 || '%' OR v.city ILIKE '%' || $1 || '%')
`

func (q *Queries) CountPublishedEvents(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (slug, title, description, venue_id, cover_image_url, status, starts_at, ends_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, title, description, venue_id, cover_image_url, status, starts_at, ends_at, metadata, created_at, updated_at
`

type CreateEventParams struct {
	Slug          string      `json:"slug"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	VenueID       pgtype.UUID `json:"venue_id"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	Status        string      `json:"status"`
	StartsAt      time.Time   `json:"starts_at"`
	EndsAt        time.Time   `json:"ends_at"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.VenueID,
		arg.CoverImageUrl,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.VenueID,
		&i.CoverImageUrl,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, slug, title, description, venue_id, cover_image_url, status, starts_at, ends_at, metadata, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.VenueID,
		&i.CoverImageUrl,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, slug, title, description, venue_id, cover_image_url, status, starts_at, ends_at, metadata, created_at, updated_at FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.VenueID,
		&i.CoverImageUrl,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedEvents = `-- name: ListPublishedEvents :many
SELECT e.id, e.slug, e.title, e.description, e.venue_id, e.cover_image_url, e.status, e.starts_at, e.ends_at, e.metadata, e.created_at, e.updated_at, v.name AS venue_name, v.city AS venue_city
FROM events e
LEFT JOIN venues v ON e.venue_id = v.id
WHERE e.status = 'published'
  AND ($1::text IS NULL OR $1 = '' OR e.title ILIKE '%' || $1 || '%' OR v.city ILIKE '%' || $1 || '%')
ORDER BY e.starts_at ASC
LIMIT $2 OFFSET $3
`

type ListPublishedEventsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPublishedEventsRow struct {
	ID            uuid.UUID   `json:"id"`
	Slug          string      `json:"slug"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	VenueID       pgtype.UUID `json:"venue_id"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	Status        string      `json:"status"`
	StartsAt      time.Time   `json:"starts_at"`
	EndsAt        time.Time   `json:"ends_at"`
	Metadata      []byte      `json:"metadata"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	VenueName     pgtype.Text `json:"venue_name"`
	VenueCity     pgtype.Text `json:"venue_city"`
}

func (q *Queries) ListPublishedEvents(ctx context.Context, arg ListPublishedEventsParams) ([]ListPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEventsRow{}
	for rows.Next() {
		var i ListPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.VenueID,
			&i.CoverImageUrl,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VenueName,
			&i.VenueCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, description = $3, venue_id = $4, cover_image_url = $5,
    status = $6, starts_at = $7, ends_at = $8, metadata = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, title, description, venue_id, cover_image_url, status, starts_at, ends_at, metadata, created_at, updated_at
`

type UpdateEventParams struct {
	ID            uuid.UUID   `json:"id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	VenueID       pgtype.UUID `json:"venue_id"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	Status        string      `json:"status"`
	StartsAt      time.Time   `json:"starts_at"`
	EndsAt        time.Time   `json:"ends_at"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.VenueID,
		arg.CoverImageUrl,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.VenueID,
		&i.CoverImageUrl,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
