// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (booking_id, gateway, gateway_ref, amount, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, booking_id, gateway, gateway_ref, amount, status, idempotency_key, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID      uuid.UUID   `json:"booking_id"`
	Gateway        string      `json:"gateway"`
	GatewayRef     pgtype.Text `json:"gateway_ref"`
	Amount         int64       `json:"amount"`
	Status         string      `json:"status"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.Gateway,
		arg.GatewayRef,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, gateway, gateway_ref, amount, status, idempotency_key, paid_at, created_at, updated_at FROM payments WHERE booking_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, gateway, gateway_ref, amount, status, idempotency_key, paid_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET status = $2, paid_at = $3, gateway_ref = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, booking_id, gateway, gateway_ref, amount, status, idempotency_key, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	GatewayRef pgtype.Text        `json:"gateway_ref"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.PaidAt,
		arg.GatewayRef,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingPaymentByBookingID = `-- name: GetPendingPaymentByBookingID :one
SELECT id, booking_id, gateway, gateway_ref, amount, status, idempotency_key, paid_at, created_at, updated_at FROM payments
WHERE booking_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT p.id, p.booking_id, p.gateway, p.gateway_ref, p.amount, p.status, p.idempotency_key, p.paid_at, p.created_at, p.updated_at FROM payments p
JOIN bookings b ON b.id = p.booking_id
WHERE b.id::text = $1
ORDER BY p.created_at DESC
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Gateway,
		&i.GatewayRef,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
