// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmSoldTickets = `-- name: ConfirmSoldTickets :one
UPDATE ticket_types
SET sold_count = sold_count + $2,
    held_count = held_count - $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND held_count >= $2
RETURNING id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at
`

type ConfirmSoldTicketsParams struct {
	ID        uuid.UUID `json:"id"`
	SoldCount int32     `json:"sold_count"`
}

func (q *Queries) ConfirmSoldTickets(ctx context.Context, arg ConfirmSoldTicketsParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, confirmSoldTickets, arg.ID, arg.SoldCount)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (
    event_id, name, price, total_quota, max_per_order, sales_start_at, sales_end_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at
`

type CreateTicketTypeParams struct {
	EventID      uuid.UUID `json:"event_id"`
	Name         string    `json:"name"`
	Price        int64     `json:"price"`
	TotalQuota   int32     `json:"total_quota"`
	MaxPerOrder  int32     `json:"max_per_order"`
	SalesStartAt time.Time `json:"sales_start_at"`
	SalesEndAt   time.Time `json:"sales_end_at"`
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Price,
		arg.TotalQuota,
		arg.MaxPerOrder,
		arg.SalesStartAt,
		arg.SalesEndAt,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementHeldCount = `-- name: DecrementHeldCount :one
UPDATE ticket_types
SET held_count = held_count - $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND held_count >= $2
RETURNING id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at
`

type DecrementHeldCountParams struct {
	ID        uuid.UUID `json:"id"`
	HeldCount int32     `json:"held_count"`
}

func (q *Queries) DecrementHeldCount(ctx context.Context, arg DecrementHeldCountParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, decrementHeldCount, arg.ID, arg.HeldCount)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypeByID = `-- name: GetTicketTypeByID :one
SELECT id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at FROM ticket_types WHERE id = $1
`

func (q *Queries) GetTicketTypeByID(ctx context.Context, id uuid.UUID) (TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeByID, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypeForUpdate = `-- name: GetTicketTypeForUpdate :one
SELECT id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at FROM ticket_types WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTicketTypeForUpdate(ctx context.Context, id uuid.UUID) (TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeForUpdate, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementHeldCount = `-- name: IncrementHeldCount :one
UPDATE ticket_types
SET held_count = held_count + $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
  AND (total_quota - sold_count - held_count) >= $2
RETURNING id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at
`

type IncrementHeldCountParams struct {
	ID        uuid.UUID `json:"id"`
	HeldCount int32     `json:"held_count"`
}

func (q *Queries) IncrementHeldCount(ctx context.Context, arg IncrementHeldCountParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, incrementHeldCount, arg.ID, arg.HeldCount)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuota,
		&i.SoldCount,
		&i.HeldCount,
		&i.MaxPerOrder,
		&i.SalesStartAt,
		&i.SalesEndAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketTypesByEvent = `-- name: ListTicketTypesByEvent :many
SELECT id, event_id, name, price, total_quota, sold_count, held_count, max_per_order, sales_start_at, sales_end_at, version, created_at, updated_at FROM ticket_types WHERE event_id = $1 ORDER BY price ASC
`

func (q *Queries) ListTicketTypesByEvent(ctx context.Context, eventID uuid.UUID) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.TotalQuota,
			&i.SoldCount,
			&i.HeldCount,
			&i.MaxPerOrder,
			&i.SalesStartAt,
			&i.SalesEndAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
