// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (booking_id, ticket_type_id, ticket_code, status)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, ticket_type_id, ticket_code, status, checked_in_at, created_at
`

type CreateTicketParams struct {
	BookingID    uuid.UUID `json:"booking_id"`
	TicketTypeID uuid.UUID `json:"ticket_type_id"`
	TicketCode   string    `json:"ticket_code"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.BookingID,
		arg.TicketTypeID,
		arg.TicketCode,
		arg.Status,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT id, booking_id, ticket_type_id, ticket_code, status, checked_in_at, created_at FROM tickets WHERE ticket_code = $1
`

func (q *Queries) GetTicketByCode(ctx context.Context, ticketCode string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByCode, ticketCode)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.TicketCode,
		&i.Status,
		&i.CheckedInAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketsByBooking = `-- name: ListTicketsByBooking :many
SELECT t.id, t.booking_id, t.ticket_type_id, t.ticket_code, t.status, t.checked_in_at, t.created_at, tt.name AS ticket_type_name
FROM tickets t
JOIN ticket_types tt ON t.ticket_type_id = tt.id
WHERE t.booking_id = $1
`

type ListTicketsByBookingRow struct {
	ID             uuid.UUID          `json:"id"`
	BookingID      uuid.UUID          `json:"booking_id"`
	TicketTypeID   uuid.UUID          `json:"ticket_type_id"`
	TicketCode     string             `json:"ticket_code"`
	Status         string             `json:"status"`
	CheckedInAt    pgtype.Timestamptz `json:"checked_in_at"`
	CreatedAt      time.Time          `json:"created_at"`
	TicketTypeName string             `json:"ticket_type_name"`
}

func (q *Queries) ListTicketsByBooking(ctx context.Context, bookingID uuid.UUID) ([]ListTicketsByBookingRow, error) {
	rows, err := q.db.Query(ctx, listTicketsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsByBookingRow{}
	for rows.Next() {
		var i ListTicketsByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TicketTypeID,
			&i.TicketCode,
			&i.Status,
			&i.CheckedInAt,
			&i.CreatedAt,
			&i.TicketTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
