// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, city, capacity, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, city, capacity, latitude, longitude, created_at, updated_at
`

type CreateVenueParams struct {
	Name      string         `json:"name"`
	Address   string         `json:"address"`
	City      string         `json:"city"`
	Capacity  int32          `json:"capacity"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Capacity,
		arg.Latitude,
		arg.Longitude,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Capacity,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, name, address, city, capacity, latitude, longitude, created_at, updated_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Capacity,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, address, city, capacity, latitude, longitude, created_at, updated_at FROM venues ORDER BY name ASC
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Capacity,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
