import type { IconType } from "react-icons";
import {
  HiOutlineArrowTopRightOnSquare,
  HiOutlineBanknotes,
  HiOutlineBookmark,
  HiOutlineBuildingOffice2,
  HiOutlineCalendarDays,
  HiOutlineChartBar,
  HiOutlineClipboardDocumentCheck,
  HiOutlineClipboardDocumentList,
  HiOutlineCog6Tooth,
  HiOutlineDocumentArrowDown,
  HiOutlineIdentification,
  HiOutlineMapPin,
  HiOutlinePhoto,
  HiOutlineQueueList,
  HiOutlineShieldCheck,
  HiOutlineSquares2X2,
  HiOutlineTag,
  HiOutlineTicket,
  HiOutlineUserGroup,
  HiOutlineUsers,
} from "react-icons/hi2";
import type { IconName } from "@/lib/admin-nav";

export const adminNavIcons: Record<IconName, IconType> = {
  dashboard: HiOutlineSquares2X2,
  events: HiOutlineCalendarDays,
  venues: HiOutlineMapPin,
  categories: HiOutlineQueueList,
  banners: HiOutlinePhoto,
  moderation: HiOutlineShieldCheck,
  bookings: HiOutlineBookmark,
  payments: HiOutlineBanknotes,
  refunds: HiOutlineArrowTopRightOnSquare,
  promos: HiOutlineTag,
  checkin: HiOutlineClipboardDocumentCheck,
  reports: HiOutlineChartBar,
  sales: HiOutlineChartBar,
  exports: HiOutlineDocumentArrowDown,
  users: HiOutlineUsers,
  organizers: HiOutlineBuildingOffice2,
  staff: HiOutlineIdentification,
  settings: HiOutlineCog6Tooth,
  audit: HiOutlineClipboardDocumentList,
  settlements: HiOutlineBanknotes,
  external: HiOutlineArrowTopRightOnSquare,
};
